(() => {
  const { createClient } = window.supabase;
  const supabase = createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY);
  const $=id=>document.getElementById(id);
  let products=[]; let cart=JSON.parse(localStorage.getItem('drapeAuraCart')||'[]'); let currentFilter='All';
  const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:0,maximumFractionDigits:2})}`;
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const totalStock=p=>(p.product_variants||[]).reduce((s,v)=>s+Number(v.stock_quantity||0),0);
  function saveCart(){localStorage.setItem('drapeAuraCart',JSON.stringify(cart));renderCart();updateCount();}
  function updateCount(){$('count').textContent=cart.reduce((s,i)=>s+i.quantity,0);}
  function open(id){$(id).classList.remove('hidden');document.body.classList.add('no-scroll');}
  function close(id){$(id).classList.add('hidden');if(!document.querySelector('.overlay:not(.hidden)'))document.body.classList.remove('no-scroll');}
  document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>close(b.dataset.close)));
  document.querySelectorAll('.overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)close(o.id)}));
  $('searchBtn').onclick=()=>{open('searchPanel');setTimeout(()=>$('searchInput').focus(),50);};
  $('accountBtn').onclick=()=>open('accountPanel'); $('cartBtn').onclick=()=>{renderCart();open('cartPanel');};
  function card(p){const stock=totalStock(p);const sold=!p.available||stock<=0;const badges=`<div class="card-badges">${p.new_arrival?'<em class="new">New Arrival</em>':''}${sold?'<em class="off">Out of Stock</em>':''}</div>`;const img=p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}" loading="lazy">`:'<span>Product image</span>';return `<article class="product-card"><button class="product-image" data-id="${p.id}">${img}${badges}</button><button class="product-name" data-id="${p.id}">${esc(p.name)}</button><p>${money(p.price)}</p><button class="add" data-id="${p.id}" ${sold?'disabled':''}>${sold?'Out of Stock':'♡  Add to Cart'}</button></article>`;}
  function renderShop(){const list=currentFilter==='All'?products:products.filter(p=>p.category===currentFilter);$('shopGrid').innerHTML=list.length?list.map(card).join(''):'<div class="loading-card">No products in this category yet.</div>';bindProductButtons();}
  function renderNew(){const list=products.filter(p=>p.new_arrival);$('newGrid').innerHTML=list.length?list.slice(0,4).map(card).join(''):'<div class="loading-card">New arrivals will appear here soon.</div>';bindProductButtons();}
  function bindProductButtons(){document.querySelectorAll('.product-image,.product-name').forEach(b=>b.onclick=()=>showProduct(b.dataset.id));document.querySelectorAll('.add').forEach(b=>b.onclick=()=>addProduct(b.dataset.id));}
  function showProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const vars=p.product_variants||[];const stock=totalStock(p);const sold=!p.available||stock<=0;let variantHtml=vars.length?`<label class="variant-select">${vars.length>1?'Choose size / colour':'Size / Colour'}<select id="detailVariant">${vars.map(v=>`<option value="${v.id}" ${Number(v.stock_quantity)<=0?'disabled':''}>${esc(v.size||'One Size')}${v.color?' — '+esc(v.color):''}${Number(v.stock_quantity)<=0?' — Out of stock':''}</option>`).join('')}</select></label>`:'';$('productDetail').innerHTML=`<div class="detail-grid"><div class="detail-image">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}">`:'Product image'}</div><div><p class="eyebrow">${esc(p.category)}</p><h2>${esc(p.name)}</h2><p class="detail-price">${money(p.price)}</p><p class="detail-description">${esc(p.description||'')}</p>${variantHtml}<button class="button full-btn" id="detailAdd" ${sold?'disabled':''}>${sold?'Out of Stock':'Add to Cart'}</button></div></div>`;if(!sold)$('detailAdd').onclick=()=>{const v=vars.length?vars.find(x=>x.id===$('detailVariant').value):null;addProduct(id,v?.id);};open('productPanel');}
  function addProduct(id,variantId=null){const p=products.find(x=>x.id===id);if(!p)return;const v=(p.product_variants||[]).find(x=>x.id===variantId) || (p.product_variants||[])[0];if(!v||Number(v.stock_quantity)<=0)return;const key=`${id}:${v.id}`;const found=cart.find(i=>i.key===key);if(found)found.quantity=Math.min(found.quantity+1,Number(v.stock_quantity));else cart.push({key,productId:id,variantId:v.id,name:p.name,variantLabel:`${v.size||'One Size'}${v.color?' — '+v.color:''}`,price:Number(v.price_override??p.price),quantity:1,maxStock:Number(v.stock_quantity),image_url:p.image_url});saveCart();}
  function renderCart(){if(!cart.length){$('cartItems').innerHTML='<div class="empty-cart">Your bag is empty.</div>';}else{$('cartItems').innerHTML=cart.map((i,idx)=>`<div class="cart-row"><div class="cart-thumb">${i.image_url?`<img src="${esc(i.image_url)}" alt="">`:''}</div><div><strong>${esc(i.name)}</strong><small>${esc(i.variantLabel)}</small><div class="qty"><button data-cart-dec="${idx}">−</button><span>${i.quantity}</span><button data-cart-inc="${idx}">+</button><button data-cart-del="${idx}" class="remove">Remove</button></div></div><b>${money(i.price*i.quantity)}</b></div>`).join('');document.querySelectorAll('[data-cart-dec]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.cartDec,-1));document.querySelectorAll('[data-cart-inc]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.cartInc,1));document.querySelectorAll('[data-cart-del]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.cartDel,1);saveCart();});}$('cartTotal').textContent=money(cart.reduce((s,i)=>s+i.price*i.quantity,0));}
  function changeQty(i,d){const item=cart[i];if(!item)return;item.quantity+=d;if(item.quantity<=0)cart.splice(i,1);else item.quantity=Math.min(item.quantity,item.maxStock);saveCart();}
  $('checkoutBtn').onclick=()=>alert('Checkout + WhatsApp ordering is the next build step. Your cart is already being saved in this browser.');
  document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;renderShop();});
  document.querySelectorAll('.cats a[data-category]').forEach(a=>a.onclick=()=>{currentFilter=a.dataset.category;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===currentFilter));setTimeout(renderShop,50);});
  $('searchInput').addEventListener('input',()=>{const q=$('searchInput').value.trim().toLowerCase();const list=q?products.filter(p=>(p.name+' '+p.category+' '+(p.description||'')).toLowerCase().includes(q)):[];$('searchResults').innerHTML=q?(list.length?list.map(p=>`<button class="search-item" data-id="${p.id}"><span>${p.image_url?`<img src="${esc(p.image_url)}" alt="">`:''}</span><strong>${esc(p.name)}</strong><small>${money(p.price)}</small></button>`).join(''):'<p class="muted-note">No products found.</p>'):'<p class="muted-note">Start typing to search the collection.</p>';document.querySelectorAll('.search-item').forEach(b=>b.onclick=()=>{close('searchPanel');showProduct(b.dataset.id);});});
  $('subscribeForm').addEventListener('submit',e=>{e.preventDefault();$('subscribeMsg').textContent='Thank you — you’re on the list.';e.target.reset();});
  async function load(){if(!window.SUPABASE_URL||!window.SUPABASE_ANON_KEY)return;const {data,error}=await supabase.from('products').select('*, product_variants(*)').eq('available',true).order('created_at',{ascending:false});if(error){console.error(error);$('shopGrid').innerHTML='<div class="loading-card">Unable to load products right now.</div>';return;}products=data||[];renderShop();renderNew();updateCount();}
  $('year').textContent=new Date().getFullYear();renderCart();load();
})();
